name: flutter_general
description: A new Flutter project.
version: 0.0.2
author: avarche <sth@gmail.com>
homepage: http://sth.ir
publish_to: http://192.168.1.10:8284

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pull_to_refresh: 2.0.0
  flutter_svg: ^0.22.0
  rxdart: ^0.27.0
  shimmer: ^2.0.0
  meta: 1.7.0
  http: ^0.13.3
  url_launcher: ^6.0.4
  shared_preferences: ^2.0.5
  path_provider: 2.0.1
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+9
  video_player: ^2.2.18
  android_intent_plus: ^3.1.1
  flutter:
    sdk: flutter


flutter:
